### 5. SVC

In [64]:
clf_5a = SVC()
CV_clf_5a = GridSearchCV(estimator=clf_5a,
                        param_grid={'C': [0.1, 1, 10, 100, 1000],  
                                  'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
                                  'kernel': ['linear', 'rbf','poly','sigmoid']},
                        cv=5,
                        scoring='roc_auc')
pipeline_5a = Pipeline([('chi2', chi2_selector),
                       ('clf_cv',CV_clf_5a)])
pipeline_5a.fit(X_train,y_train)
y_predict_5a = pipeline_5a.predict(X_test)

In [67]:
evaluation_result(y_predict_5a, y_test)

Accuracy is: 0.754
F1 score is: 0.5060240963855421
Precision is: 0.6774193548387096
Recall is: 0.40384615384615385
Kappa score is: 0.355913032549956
AUC is: 0.6583184257602862
Balanced accuracy is: 0.6583184257602862
[[314  93]
 [ 30  63]]


In [69]:
dump(pipeline_5a, '/Users/jihunlee/Desktop/svc.joblib')

['/Users/jihunlee/Desktop/svc.joblib']

### 6. MLP Classifier

In [61]:
parameters={
    'solver': ['lbfgs'],
    'learning_rate': ["constant", "invscaling", "adaptive"],
    'hidden_layer_sizes':np.arange(5, 10),
    'alpha': 10.0 ** -np.arange(1, 3),
    'activation': ["logistic", "relu", "tanh", 'identity'],
    'random_state':[42]
}

CV_clf_6 = GridSearchCV(estimator=MLPClassifier(),
                        param_grid=parameters,
                        cv=5)

pipeline_6 = Pipeline([('chi2', chi2_selector), 
                       ('clf_cv', CV_clf_6)])

pipeline_6.fit(X_train, y_train)
y_predict_6 = pipeline_6.predict(X_test)

In [62]:
evaluation_result(y_predict_6, y_test)

Accuracy is: 0.766
F1 score is: 0.5836298932384342
Precision is: 0.656
Recall is: 0.5256410256410257
Kappa score is: 0.4236453201970444
AUC is: 0.7003205128205128
Balanced accuracy is: 0.7003205128205128
[[301  74]
 [ 43  82]]


In [65]:
from joblib import dump, load

In [66]:
dump(pipeline_6, '/Users/jihunlee/Desktop/mlpclassifier.joblib')

['/Users/jihunlee/Desktop/mlpclassifier.joblib']

### 7. Gaussian Naive Bayes

In [50]:
clf_featr_sele_7 = GaussianNB()
pipeline_7 = Pipeline([('chi2', chi2_selector), ('gaussianProcess', clf_featr_sele_7)])
pipeline_7.fit(X_train, y_train)
y_predict_7 = pipeline_7.predict(X_test)

In [51]:
evaluation_result(y_predict_7, y_test)

Accuracy is: 0.686
F1 score is: 0.6084788029925186
Precision is: 0.49795918367346936
Recall is: 0.782051282051282
Kappa score is: 0.36724165726261493
AUC is: 0.7122465712581991
Balanced accuracy is: 0.7122465712581991
[[221  34]
 [123 122]]


### 8. K Nearest Neighbors

In [56]:
clf_featr_sele_8 = KNeighborsClassifier()
CV_clf_8 = GridSearchCV(
    clf_featr_sele_8,
    {'n_neighbors': [3,5,7,9,11],
    'weights':['uniform','distance'],
    'metric':['euclidean','manhattan']
    },
    cv=5,
    n_jobs=-1)
pipeline_8 = Pipeline([('chi2', chi2_selector), 
                       ('clf_cv', CV_clf_8)])

pipeline_8.fit(X_train, y_train)
y_predict_8 = pipeline_8.predict(X_test)

In [49]:
evaluation_result(y_predict_8, y_test)

Accuracy is: 0.712
F1 score is: 0.5443037974683544
Precision is: 0.5375
Recall is: 0.5512820512820513
Kappa score is: 0.3338267949666913
AUC is: 0.668082886106142
Balanced accuracy is: 0.6680828861061419
[[270  70]
 [ 74  86]]


### 9. Gaussian Process

In [45]:
kernel = 1.0 * RBF(1.0)
clf_featr_sele_9 = GaussianProcessClassifier(kernel=kernel,
        random_state=42)
pipeline_9 = Pipeline([('chi2', chi2_selector), ('gaussianProcess', clf_featr_sele_9)])
pipeline_9.fit(X_train, y_train)
y_predict_9 = pipeline_9.predict(X_test)

In [46]:
evaluation_result(y_predict_9, y_test)

Accuracy is: 0.764
F1 score is: 0.5874125874125874
Precision is: 0.6461538461538462
Recall is: 0.5384615384615384
Kappa score is: 0.42405310425614995
AUC is: 0.7023703041144901
Balanced accuracy is: 0.7023703041144902
[[298  72]
 [ 46  84]]
